---
title: "Hand-Extracted Node and Edge Tables"
author: "Bob"
date: "2025-09-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library('dplyr')
```

# Examples of node and edge tables hand-extracted from WinBUGS examples

## Rats

```{r rats}
nodes <- 'label, plate
tau.alpha, none
alpha.c, none
alpha0, none
beta.c, none
tau.beta, none
sigma.alpha, none
tau.c, none
sigma, none
sigma.beta, none
alpha[i], i
beta[i], i
"mu[i,j]", ij
"Y[i,j]", ij
x[j], j
' %>% gsub(' ', '', .) %>% textConnection %>% read.csv

edges <- 'from, to, category
sigma.alpha, tau.alpha, logical
tau.alpha, alpha[i], stochastic
alpha.c, alpha[i], stochastic
alpha.c, alpha0, logical
beta.c, alpha0, logical
beta.c, beta[i], stochastic
tau.beta, beta[i], stochastic
sigma.beta, tau.beta, logical
tau.c, sigma, logical
tau.c, "Y[i,j]", stochastic
alpha[i], "mu[i,j]", logical
beta[i], "mu[i,j]", logical
x[j], "mu[i,j]", logical
"mu[i,j]", "Y[i,j]", logical
' %>% gsub(' ', '', .) %>% textConnection %>% read.csv

```


## Draw the graph

```{r draw_graph}
library(igraph)

g <- graph_from_edgelist(as.matrix(edges[c('from', 'to')]), directed = TRUE)

plot(g,
     vertex.label.cex = 0.8,
     vertex.label.color = "black",
     vertex.color = "lightblue",
     edge.arrow.size = 0.2,
     layout = layout_with_kk)

```


from `?plot.igraph`:

"One convenient way to plot graphs is to plot with tkplot() first, handtune the placement of the vertices, query the coordinates by the tk_coords() function and use them with plot() to plot the graph to any R device."

```{r data}
data <- list(
	x = c(8.0, 15.0, 22.0, 29.0, 36.0), 
	xbar = 22, 
	N = 30, 
	T = 5, 
	Y = structure(
		.Data = c(151, 199, 246, 283, 320, 
							145, 199, 249, 293, 354, 
							147, 214, 263, 312, 328, 
							155, 200, 237, 272, 297, 
							135, 188, 230, 280, 323, 
							159, 210, 252, 298, 331, 
							141, 189, 231, 275, 305, 
							159, 201, 248, 297, 338, 
							177, 236, 285, 350, 376, 
							134, 182, 220, 260, 296, 
							160, 208, 261, 313, 352, 
							143, 188, 220, 273, 314, 
							154, 200, 244, 289, 325, 
							171, 221, 270, 326, 358, 
							163, 216, 242, 281, 312, 
							160, 207, 248, 288, 324,
							142, 187, 234, 280, 316, 
							156, 203, 243, 283, 317, 
							157, 212, 259, 307, 336, 
							152, 203, 246, 286, 321, 
							154, 205, 253, 298, 334, 
							139, 190, 225, 267, 302, 
							146, 191, 229, 272, 302, 
							157, 211, 250, 285, 323, 
							132, 185, 237, 286, 331, 
							160, 207, 257, 303, 345, 
							169, 216, 261, 295, 333, 
							157, 205, 248, 289, 316, 
							137, 180, 219, 258, 291, 
							153, 200, 244, 286, 324),
		.Dim = c(30,5)
	)
)

rbow <- rainbow(nrow(data$Y), end=2/3, v=0.8)
plot(data$x, data$Y[1,], type='n', 
		 ylim=c(min(data$Y), max(data$Y)),
		 xlab='days', ylab='grams')
for (rat in 1:nrow(data$Y)){
	lines(data$x, data$Y[rat,], col=rbow[rat], lwd=3)
	points(data$x, data$Y[rat,], col=rbow[rat], cex=0.5)
}

```
```{r jags_model}
model_code <- "model {
	for( i in 1 : N ) { 
		for( j in 1 : T ) {
			Y[i , j] ~ dnorm(mu[i , j],tau.c)
			mu[i , j] <- alpha[i] + beta[i] * (x[j] - xbar) 
		}
		alpha[i] ~ dnorm(alpha.c,tau.alpha)
		beta[i] ~ dnorm(beta.c,tau.beta)
	}
	tau.c ~ dgamma(0.001,0.001)
	sigma <- 1 / sqrt(tau.c)
	alpha.c ~ dnorm(0.0,1.0E-6)
	
	# Choice of prior of random effects variances 
	# Prior 1: uniform on SD
	sigma.alpha ~ dunif(0,100)
	sigma.beta ~ dunif(0,100)
	tau.alpha <- 1/(sigma.alpha*sigma.alpha)
	tau.beta<-1/(sigma.beta*sigma.beta)
	
	# Prior 2: (not recommended)
	#tau.alpha ~ dgamma(0.001,0.001)
	#tau.beta ~ dgamma(0.001,0.001)
	
	beta.c ~ dnorm(0.0,1.0E-6)
	alpha0 <- alpha.c - xbar * beta.c
}
"
```
